Build/Test Tools: Improve `env:install` command with better configurability and error handling.
* Force WP-CLI to use the `wp-config.php` in the directory above the `src` directory via the `WP_CONFIG_PATH` environment variable [read by WP-CLI](https://github.com/wp-cli/wp-cli/blob/2800ad0a66747a826ae4221b2f022f1df6779cb6/php/utils.php#L328-L329) in the `wp_locate_config()` function.
* Update the `env:install` command to write out the config at the repo root instead of writing it inside of the `ABSPATH` only then to move it one directory up.
* Fix JSHint issues.
* Add error handling to when `npm run env:install` is executed without having first done `npm run env:start`, in which case the script will end with an exit code of 1 and emit:

> Error: It appears the development environment has not been started. Message: Timed out waiting for: tcp:localhost:8000
> Did you forget to do 'npm run env:start'?

Fixes #63543.
Props westonruter, jorbin, SirLouen.

Built from https://develop.svn.wordpress.org/trunk@60305


git-svn-id: http://core.svn.wordpress.org/trunk@59641 1a063a9b-81f0-0310-95a4-ce76da25c4cd